# Generated by Django 5.0.4 on 2024-10-24 21:00

import django.core.validators
import django.db.models.deletion
import fruits.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0002_rename_image_irl_profile_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fruit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'unique': 'This fruit name is already in use! Try a new one.'}, max_length=30, unique=True, validators=[django.core.validators.MinLengthValidator(2), fruits.validators.AlphaNumericValidator()])),
                ('image_url', models.URLField()),
                ('description', models.TextField()),
                ('nutrition', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fruits', to='profiles.profile')),
            ],
        ),
    ]
