# Generated by Django 5.0.4 on 2024-10-24 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fruit',
            name='nutrition',
            field=models.TextField(blank=True, null=True),
        ),
    ]
